In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\Administrator\Desktop\杂货店\球星比赛数据\James_Harden.csv')

In [3]:
df.tail()

     对手 胜负 主客场  命中  投篮数  投篮命中率  3分命中率  篮板  助攻  得分
20  步行者  胜   主   8   22  0.364  0.333   8  10  29
21   湖人  胜   客  13   22  0.591  0.444   4   9  36
22   爵士  胜   客   8   19  0.421  0.333   5   3  29
23  开拓者  胜   客  16   29  0.552  0.571   8   3  48
24   鹈鹕  胜   主   8   16  0.500  0.400   1  17  26

In [4]:
#pivot_table(data, values=None, index=None,
# columns=None,aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')

In [5]:
#pivot_table有四个最重要的参数index、values、columns、aggfunc

Index就是层次字段，要通过透视表获取什么信息就按照相应的顺序设置字段

In [6]:
#将对手设置为index
pd.pivot_table(df,index=['对手'])

       3分命中率     助攻    命中     得分   投篮命中率   投篮数    篮板
对手
76人  0.33950  10.00   9.0  28.00  0.4405  20.5   3.5
勇士   0.44400  11.00  10.0  27.00  0.4350  23.0   6.0
国王   0.28600   9.00   8.0  27.00  0.3810  21.0   3.0
太阳   0.54500   7.00  12.0  48.00  0.5450  22.0   2.0
小牛   0.46200   7.00  10.0  29.00  0.5260  19.0   3.0
尼克斯  0.36900   9.50  10.5  34.00  0.4175  25.0   3.5
开拓者  0.57100   3.00  16.0  48.00  0.5520  29.0   8.0
掘金   0.14300   9.00   6.0  21.00  0.3750  16.0   8.0
步行者  0.29150  12.50   8.5  27.50  0.3965  21.5   6.5
湖人   0.44400   9.00  13.0  36.00  0.5910  22.0   4.0
灰熊   0.35025   7.75   8.5  27.25  0.4015  21.0   4.5
爵士   0.60400   8.00  13.5  42.50  0.5905  22.0   3.5
猛龙   0.27300  11.00   8.0  38.00  0.3200  25.0   6.0
篮网   0.61500   8.00  13.0  37.00  0.6500  20.0  10.0
老鹰   0.54500  11.00   8.0  29.00  0.5330  15.0   3.0
骑士   0.42900  13.00   8.0  35.00  0.3810  21.0  11.0
鹈鹕   0.40000  17.00   8.0  26.00  0.5000  16.0   1.0
黄蜂   0.40000  11.00   8.0  27.00  0.4440  18.0  10.0

In [7]:
#将胜负设置为index
pd.pivot_table(df,index=['胜负'])

      3分命中率        助攻         命中         得分     投篮命中率        投篮数        篮板
胜负
胜   0.42819  9.666667  10.238095  32.952381  0.481524  21.142857  5.142857
负   0.29350  8.500000   7.500000  27.250000  0.354250  21.250000  4.750000

In [8]:
#将主客场设置为index
pd.pivot_table(df,index=['主客场'])

        3分命中率         助攻        命中         得分     投篮命中率        投篮数        篮板
主客场
主    0.418583  10.083333  9.916667  33.083333  0.461750  21.416667  5.333333
客    0.395615   8.923077  9.692308  31.076923  0.460615  20.923077  4.846154

In [9]:
#对手与主客场都设置为index，其实就变成为了两层索引
pd.pivot_table(df,index=[u'对手',u'主客场'])

          3分命中率    助攻    命中    得分  投篮命中率   投篮数    篮板
对手  主客场
76人 主    0.4290   7.0   8.0  29.0  0.381  21.0   4.0
    客    0.2500  13.0  10.0  27.0  0.500  20.0   3.0
勇士  客    0.4440  11.0  10.0  27.0  0.435  23.0   6.0
国王  客    0.2860   9.0   8.0  27.0  0.381  21.0   3.0
太阳  客    0.5450   7.0  12.0  48.0  0.545  22.0   2.0
小牛  主    0.4620   7.0  10.0  29.0  0.526  19.0   3.0
尼克斯 主    0.3850  10.0  12.0  37.0  0.444  27.0   2.0
    客    0.3530   9.0   9.0  31.0  0.391  23.0   5.0
开拓者 客    0.5710   3.0  16.0  48.0  0.552  29.0   8.0
掘金  主    0.1430   9.0   6.0  21.0  0.375  16.0   8.0
步行者 主    0.3330  10.0   8.0  29.0  0.364  22.0   8.0
    客    0.2500  15.0   9.0  26.0  0.429  21.0   5.0
湖人  客    0.4440   9.0  13.0  36.0  0.591  22.0   4.0
灰熊  主    0.3395   8.0   9.5  30.0  0.420  22.5   4.5
    客    0.3610   7.5   7.5  24.5  0.383  19.5   4.5
爵士  主    0.8750  13.0  19.0  56.0  0.760  25.0   2.0
    客    0.3330   3.0   8.0  29.0  0.421  19.0   5.0
猛龙  主    0.2730  11.0   8.0  38.0  0.320  25.0   6.0
篮网  主    0.6150   8.0  13.0  37.0  0.650  20.0  10.0
老鹰  客    0.5450  11.0   8.0  29.0  0.533  15.0   3.0
骑士  主    0.4290  13.0   8.0  35.0  0.381  21.0  11.0
鹈鹕  主    0.4000  17.0   8.0  26.0  0.500  16.0   1.0
黄蜂  客    0.4000  11.0   8.0  27.0  0.444  18.0  10.0

我们只需要james harden在主客场和不同胜负情况下的得分、篮板与助攻三项数据

In [10]:
pd.pivot_table(df,index=[u'主客场',u'胜负'],values=[u'得分',u'助攻',u'篮板'])

               助攻         得分        篮板
主客场 胜负
主   胜   10.555556  34.222222  5.444444
    负    8.666667  29.666667  5.000000
客   胜    9.000000  32.000000  4.916667
    负    8.000000  20.000000  4.000000

aggfunc默认为平均数，可以设置我们对数据聚合时进行的函数操作

In [11]:
pd.pivot_table(df,index=[u'主客场',u'胜负'],values=[u'得分',u'助攻',u'篮板'],aggfunc=[np.sum,np.mean])

        sum                mean
         助攻   得分  篮板         助攻         得分        篮板
主客场 胜负
主   胜    95  308  49  10.555556  34.222222  5.444444
    负    26   89  15   8.666667  29.666667  5.000000
客   胜   108  384  59   9.000000  32.000000  4.916667
    负     8   20   4   8.000000  20.000000  4.000000

Columns类似Index可以设置列层次字段，它不是一个必要参数，作为一种分割数据的可选方式。
fill_value填充空值，默认为NAN,margins=True进行汇总，汇总的字段为‘All’

In [12]:
pd.pivot_table(df,index=[u'主客场'],columns=[u'对手'],values=[u'得分'],aggfunc=[np.sum])

      sum                                                                    \
       得分
对手    76人    勇士    国王    太阳    小牛   尼克斯   开拓者    掘金   步行者    湖人    灰熊    爵士
主客场
主    29.0   NaN   NaN   NaN  29.0  37.0   NaN  21.0  29.0   NaN  60.0  56.0
客    27.0  27.0  27.0  48.0   NaN  31.0  48.0   NaN  26.0  36.0  49.0  29.0



对手     猛龙    篮网    老鹰    骑士    鹈鹕    黄蜂
主客场
主    38.0  37.0   NaN  35.0  26.0   NaN
客     NaN   NaN  29.0   NaN   NaN  27.0

In [13]:
pd.pivot_table(df,index=[u'主客场'],columns=[u'对手'],values=[u'得分'],aggfunc=[np.sum],fill_value=0)

    sum
     得分
对手  76人  勇士  国王  太阳  小牛 尼克斯 开拓者  掘金 步行者  湖人  灰熊  爵士  猛龙  篮网  老鹰  骑士  鹈鹕  黄蜂
主客场
主    29   0   0   0  29  37   0  21  29   0  60  56  38  37   0  35  26   0
客    27  27  27  48   0  31  48   0  26  36  49  29   0   0  29   0   0  27

In [14]:
pd.pivot_table(df,index=[u'主客场'],columns=[u'对手'],values=[u'得分'],aggfunc=[np.sum],fill_value=0,margins=1)

    sum                                                                       \
     得分
对手  76人  勇士  国王  太阳  小牛 尼克斯 开拓者  掘金 步行者  湖人   灰熊  爵士  猛龙  篮网  老鹰  骑士  鹈鹕  黄蜂
主客场
主    29   0   0   0  29  37   0  21  29   0   60  56  38  37   0  35  26   0
客    27  27  27  48   0  31  48   0  26  36   49  29   0   0  29   0   0  27
All  56  27  27  48  29  68  48  21  55  36  109  85  38  37  29  35  26  27



对手   All
主客场
主    397
客    404
All  801